In [95]:
import numpy as np
from scipy.stats._continuous_distns import _digammainv
from scipy.special import digamma

In [96]:
alpha = np.random.gamma(1, 1, 10)
samples = np.random.dirichlet(alpha, 1000)
alpha

array([0.16977405, 1.21056234, 2.77021185, 0.61632493, 0.35530837,
       0.04510913, 0.34576634, 0.34996197, 1.4987906 , 1.06746012])

In [97]:
def estimate_1():
    a = np.ones(10) * 2 / 10

    for _ in range(1000):
        a = np.vectorize(_digammainv)(digamma(np.sum(a)) + np.log(samples).mean(axis=0))

    return a

In [98]:
estimate_1()

array([0.16974449, 1.24197326, 2.85404119, 0.59260869, 0.36408666,
       0.04628738, 0.33656734, 0.36737494, 1.54333726, 1.09568957])

In [99]:
def estimate_2():
    return np.vectorize(_digammainv)(digamma(np.sum(alpha)) + np.log(samples).mean(axis=0))

In [100]:
estimate_2()

array([0.16911602, 1.22336384, 2.800394  , 0.58653875, 0.36146388,
       0.04623892, 0.33429121, 0.36470955, 1.51836961, 1.0800886 ])