In [79]:
import numpy as np
from scipy.stats._continuous_distns import _digammainv
from scipy.special import digamma

In [95]:
alpha = np.random.gamma(1, 1, 10)
alpha /= 0.1 * alpha.sum()
samples = np.random.dirichlet(alpha, 10000)
alpha, sum(alpha)

(array([0.73315156, 0.26653941, 2.11235896, 0.96560241, 0.90868645,
        1.60801849, 0.48705893, 0.76858858, 2.01629657, 0.13369864]),
 np.float64(9.999999999999998))

In [96]:
def estimate_1():
    a = np.ones(10) * 2 / 10

    for _ in range(1000):
        a = np.vectorize(_digammainv)(digamma(np.sum(a)) + np.log(samples).mean(axis=0))

    return a

In [97]:
estimate_1(), sum(estimate_1())

(array([0.73507947, 0.27042103, 2.114327  , 0.96745317, 0.89776739,
        1.6200723 , 0.49090667, 0.76790149, 2.01957366, 0.13299391]),
 np.float64(10.016496092440258))

In [98]:
def estimate_2():
    return np.vectorize(_digammainv)(digamma(np.sum(alpha)) + np.log(samples).mean(axis=0))

In [99]:
estimate_2(), sum(estimate_2())

(array([0.73441918, 0.27030432, 2.11144897, 0.96645013, 0.89686983,
        1.61802158, 0.49056646, 0.76719452, 2.01685537, 0.13296399]),
 np.float64(10.005094353467758))

In [100]:
digamma(np.sum(alpha)) - digamma(alpha[0]) + np.log(samples).mean(axis=0)[0]

np.float64(0.0033345218651579245)