In [1]:
import numpy as np
from scipy.stats._continuous_distns import _digammainv
from scipy.special import digamma

In [2]:
alpha = np.random.gamma(1, 1, 10)
alpha /= 0.1 * alpha.sum()
samples = np.random.dirichlet(alpha, 10000)
alpha, sum(alpha)

(array([2.38045158, 1.04081511, 0.9097523 , 0.34745999, 1.36958778,
        0.97541793, 0.518269  , 0.17365085, 0.83038032, 1.45421514]),
 np.float64(9.999999999999998))

In [5]:
def estimate_1():
    a = np.ones(10) * 2 / 10

    for _ in range(1000):
        a = np.vectorize(_digammainv)(digamma(np.sum(a)) + np.log(samples).mean(axis=0))

    return a

In [6]:
estimate_1(), sum(estimate_1())

(array([2.39895852, 1.03643842, 0.90333521, 0.34805184, 1.36076576,
        0.97726007, 0.52806048, 0.1748804 , 0.84080839, 1.46198064]),
 np.float64(10.030539733011096))

In [98]:
def estimate_2():
    return np.vectorize(_digammainv)(digamma(np.sum(alpha)) + np.log(samples).mean(axis=0))

In [99]:
estimate_2(), sum(estimate_2())

(array([0.73441918, 0.27030432, 2.11144897, 0.96645013, 0.89686983,
        1.61802158, 0.49056646, 0.76719452, 2.01685537, 0.13296399]),
 np.float64(10.005094353467758))

In [100]:
digamma(np.sum(alpha)) - digamma(alpha[0]) + np.log(samples).mean(axis=0)[0]

np.float64(0.0033345218651579245)